Traceback (most recent call last):
  File "<pyshell#32>", line 2, in <module>
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/asaquelares/Documents/python-training/traceback-import.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
